# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: \
      PUB_CACHE = /workspace/.pub-cache
      dart pub activate mono_repo
      mono_repo pub get
    command: \
      echo $PUB_CACHE
      PATH="$PATH":"$PUB_CACHE"


image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "false in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

vscode:
  extensions:
    - dart-code.dart-code
    - ryanluker.vscode-coverage-gutters
