# 
# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: statecharts
description: Statechart implementation consistent with Harel notation and the SCXML spec
version: 1.0.1+1
homepage: https://github.com/sarahec/statecharts

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0 
  logging: ^1.0.0
  meta: ^1.7.0
  ordered_set: ^3.0.0
  quiver: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.6
  built_value_generator: ^8.1.0
  pedantic: ^1.4.0
  test: ^1.16.8
